name: Publish Quarto site
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with: { use-public-rspm: true }
      - run: quarto render
      - uses: quarto-dev/quarto-actions/publish@v2
        with: { target: gh-pages }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
